[project]
name = "axe-cli-wire-messages"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "axe",
    "rich",
]

[tool.uv.sources]
axe = { path = "../../" }
